DROP TABLE Tasks IF EXISTS;
Drop TABLE Todo IF EXISTS;
DROP TABLE Customers IF EXISTS;


CREATE TABLE Customers (
	cid integer generated by default as identity,
	username varchar (20) not null,
	password varchar (20) not null,
	email varchar (20) not null,
	primary key (cid)
);

CREATE TABLE Todo (
	todoID integer not null AUTO_INCREMENT,
	primary key (todoID),
	fk_cid integer not null,
	foreign key (fk_cid) references Customers (cid) On DELETE CASCADE
);
	
CREATE TABLE Tasks (
	taskID integer not null AUTO_INCREMENT,
	fk_todoID integer not null,
	foreign key (fk_todoID) references Todo (todoID) ON DELETE CASCADE
	task varchar (20)
);

ALTER TABLE Customers
ADD CONSTRAINT UK_8qrhl5wlohdjoko9nrorkdjkp UNIQUE (name);